import React from 'react';

interface ProductGuideProps {
  onNavigateToStudio: () => void;
  onNavigateToLanding: () => void;
}

interface GuideStep {
  number: string;
  title: string;
  badge: string;
  description: string;
  features: string[];
  visualTag: string;
  icon: string;
}

const GUIDE_STEPS: GuideStep[] = [
  {
    number: '01',
    title: 'Input Pharmacophore & Optimization Goals',
    badge: 'Input Phase',
    icon: '💊',
    visualTag: 'Compound Selector & Sliders',
    description:
      'Enter any compound name (e.g. Ampicillin, Aspirin) or custom SMILES string. Alternatively, click any 1-Click Research Preset. Customize optimization weights across Absorption, Activity, Solubility, and Toxicity penalties.',
    features: [
      'Automatic PubChem name-to-SMILES resolution',
      'Normalized multi-objective priority sliders (summing to 100%)',
      'Preset library for beta-lactams, NSAIDs, and analgesics',
    ],
  },
  {
    number: '02',
    title: 'Hardware 3D WebGL Molecular Simulation',
    badge: '3D Simulation',
    icon: '🌐',
    visualTag: 'Three.js 3D Conformer',
    description:
      'Inspect true 3D spatial conformations generated by RDKit ETKDGv3 and optimized with MMFF94 force-field energy minimization. Switch dynamically between Ball & Stick, Space-Filling CPK, and Wireframe.',
    features: [
      'Mouse drag rotation, mouse wheel zoom, and auto-spin controls',
      'Atom raycaster hover HUD displaying Element, 3D (X,Y,Z) coords, and formal charge',
      'Toggleable 3D Receptor Pocket cavity simulating target active sites',
    ],
  },
  {
    number: '03',
    title: 'Ghost Hypothesis Chemical Synthesis',
    badge: 'CAD Editor',
    icon: '✨',
    visualTag: 'Lighter Shade Isomers',
    description:
      'Edit atoms or synthesize new chemical branches like a CAD software. Clicking any atom displays holographic lighter-shade "Ghost" branches indicating available structural isomers before permanently bonding.',
    features: [
      'Lighter-shade translucent preview of structural isomers',
      'Reactive palette: Hydroxyl, Amine, Carboxyl, Prodrug Esters (POM), Fluorophenyl',
      'Click "Solidify Bond" to commit changes with instant QSAR score recalculation',
    ],
  },
  {
    number: '04',
    title: 'Chess-Style Decision Tree & Evidence Mapping',
    badge: 'Evaluation Engine',
    icon: '♟️',
    visualTag: 'React Flow Tree & Move Eval',
    description:
      'Explore candidate branches through a strategic decision tree. Each transformation receives a chess-style evaluation (e.g. Brilliant Move +2.85 for prodrug esterification) and cross-checks PubChem, ChEMBL, and BindingDB.',
    features: [
      'Grandmaster centipawn-style move evaluation annotations',
      'Pareto frontier radar charts comparing all candidates simultaneously',
      'Triple-database verification distinguishing experimentally reported vs novel candidates',
    ],
  },
];

export const ProductGuide: React.FC<ProductGuideProps> = ({
  onNavigateToStudio,
  onNavigateToLanding,
}) => {
  return (
    <div className="min-h-screen p-6 md:p-12 space-y-16 max-w-7xl mx-auto animate-fade-in text-slate-100">
      {/* Header */}
      <section className="text-center space-y-4 pt-4">
        <div className="flex justify-center items-center mb-1">
          <div className="relative group">
            <div className="absolute -inset-1 bg-gradient-to-r from-cyan-400 to-indigo-500 rounded-full blur-md opacity-60 group-hover:opacity-100 transition duration-300"></div>
            <img
              src="/Pharm_AI_Synapse_Logo.png"
              alt="Pharm AI Synapse"
              className="relative w-20 h-20 rounded-full object-cover border border-cyan-400/60 shadow-xl shadow-cyan-500/20"
            />
          </div>
        </div>

        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-cyan-950/60 border border-cyan-500/40 text-cyan-300 text-xs font-bold tracking-wide">
          <span>📖 Commercial Platform Guide & Feature Tour</span>
        </div>

        <h1 className="text-3xl md:text-5xl font-black tracking-tight text-white">
          How to Use <span className="bg-clip-text text-transparent bg-gradient-to-r from-cyan-400 via-indigo-300 to-purple-400">Pharm AI Synapse</span>
        </h1>

        <p className="text-sm md:text-base text-slate-300 max-w-2xl mx-auto leading-relaxed">
          Master the complete AI drug discovery workflow, from 3D molecular CAD manipulation to QSAR Pareto ranking and evidence verification.
        </p>

        <div className="flex items-center justify-center gap-3 pt-2">
          <button
            onClick={onNavigateToStudio}
            className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 via-purple-600 to-cyan-500 text-white font-bold text-xs shadow-lg shadow-indigo-500/25 hover:shadow-indigo-500/40 active:scale-95 transition-all cursor-pointer"
          >
            🚀 Launch AI Chatbot & 3D CAD Studio →
          </button>
          <button
            onClick={onNavigateToLanding}
            className="px-4 py-2.5 rounded-xl bg-slate-900 border border-slate-700 text-slate-300 hover:text-white font-semibold text-xs transition-all cursor-pointer"
          >
            ← Back to Showcase
          </button>
        </div>
      </section>

      {/* Step-by-Step Interactive Guide Cards */}
      <section className="space-y-8">
        {GUIDE_STEPS.map((step, idx) => (
          <div
            key={step.number}
            className="p-6 md:p-8 rounded-3xl bg-slate-900/80 border border-slate-800 hover:border-indigo-500/40 shadow-2xl space-y-6 backdrop-blur-xl transition-all"
          >
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-4">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-indigo-600 to-purple-600 flex items-center justify-center text-white font-black text-lg shadow-lg">
                  {step.number}
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="text-lg font-black text-white">{step.title}</h3>
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-indigo-500/15 text-indigo-300 border border-indigo-500/30">
                      {step.badge}
                    </span>
                  </div>
                  <p className="text-xs text-slate-300 mt-0.5">{step.description}</p>
                </div>
              </div>

              <span className="text-3xl hidden md:block">{step.icon}</span>
            </div>

            {/* Visual Simulated Mockup Box */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-center">
              <div className="lg:col-span-7 p-5 rounded-2xl bg-slate-950/90 border border-indigo-500/20 shadow-inner space-y-3">
                <div className="flex items-center justify-between text-[11px] font-bold text-slate-300 border-b border-slate-800 pb-2">
                  <span className="flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-emerald-400" />
                    Interface Simulation: {step.visualTag}
                  </span>
                  <span className="font-mono text-cyan-300 text-[10px]">Pharm AI Synapse 3D UI</span>
                </div>

                {idx === 0 && (
                  <div className="space-y-2 text-xs">
                    <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800 flex items-center justify-between">
                      <span className="text-slate-300">Target Compound:</span>
                      <span className="font-mono text-indigo-300 font-bold">Ampicillin (CID 6249)</span>
                    </div>
                    <div className="grid grid-cols-3 gap-2 text-center text-[10px]">
                      <div className="p-2 rounded bg-indigo-950/40 border border-indigo-500/30 text-indigo-300 font-bold">Oral Absorption (40%)</div>
                      <div className="p-2 rounded bg-purple-950/40 border border-purple-500/30 text-purple-300 font-bold">Activity (30%)</div>
                      <div className="p-2 rounded bg-red-950/40 border border-red-500/30 text-red-300 font-bold">Low Toxicity (20%)</div>
                    </div>
                  </div>
                )}

                {idx === 1 && (
                  <div className="h-32 rounded-xl bg-gradient-to-tr from-slate-900 via-indigo-950/40 to-slate-900 border border-indigo-500/30 flex items-center justify-center relative overflow-hidden">
                    <div className="w-16 h-16 rounded-full border border-indigo-400/40 animate-ping absolute" />
                    <div className="flex items-center gap-3 text-xs font-bold text-white z-10">
                      <span className="px-2.5 py-1 rounded bg-indigo-600 text-[10px]">3D Ball & Stick</span>
                      <span className="px-2.5 py-1 rounded bg-slate-800 text-[10px] text-slate-300">Space-Fill CPK</span>
                      <span className="px-2.5 py-1 rounded bg-cyan-950 text-[10px] text-cyan-300 border border-cyan-500/40">Receptor Pocket [ON]</span>
                    </div>
                  </div>
                )}

                {idx === 2 && (
                  <div className="p-3 rounded-xl bg-slate-900 border border-cyan-500/30 space-y-2 text-xs">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-cyan-300">Ghost Hypothesis: -POM Prodrug Ester</span>
                      <span className="text-[10px] px-2 py-0.5 rounded bg-cyan-500/20 text-cyan-300">3 Isomers Formed</span>
                    </div>
                    <p className="text-[11px] text-slate-300">
                      Lighter-shade holographic bonds displayed in 3D canvas. Click "Solidify Bond" to commit changes.
                    </p>
                  </div>
                )}

                {idx === 3 && (
                  <div className="grid grid-cols-2 gap-2 text-xs">
                    <div className="p-2.5 rounded-lg bg-emerald-950/40 border border-emerald-500/40 space-y-1">
                      <span className="font-bold text-emerald-300 text-[11px] block">🌟 Brilliant Move (+2.85 Eval)</span>
                      <p className="text-[10px] text-slate-300">Pivampicillin: Lipophilicity prodrug solves bioavailability barrier.</p>
                    </div>
                    <div className="p-2.5 rounded-lg bg-indigo-950/40 border border-indigo-500/40 space-y-1">
                      <span className="font-bold text-indigo-300 text-[11px] block">Triangulated Evidence: Reported</span>
                      <p className="text-[10px] text-slate-300">Found in PubChem & ChEMBL experimental bioassays.</p>
                    </div>
                  </div>
                )}
              </div>

              {/* Bullet points */}
              <div className="lg:col-span-5 space-y-2.5">
                <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider">Key Capabilities</h4>
                <div className="space-y-2">
                  {step.features.map((feat, fIdx) => (
                    <div key={fIdx} className="flex items-start gap-2.5 text-xs text-slate-300">
                      <span className="text-emerald-400 font-bold mt-0.5">✓</span>
                      <span>{feat}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        ))}
      </section>

      {/* Call to Action Footer */}
      <section className="text-center p-8 rounded-3xl bg-gradient-to-r from-indigo-900/60 via-purple-900/40 to-cyan-900/60 border border-indigo-500/30 shadow-2xl space-y-4">
        <h3 className="text-2xl font-black text-white">Experience the 3D Synthesis Laboratory</h3>
        <p className="text-xs text-slate-300 max-w-md mx-auto">
          Try the Gemini-style chatbot, upload files, modify atoms with ghost hypothesis, and view side-by-side 3D models.
        </p>
        <button
          onClick={onNavigateToStudio}
          className="px-8 py-3.5 rounded-2xl bg-gradient-to-r from-cyan-500 via-indigo-600 to-purple-600 text-white font-black text-sm tracking-wide shadow-2xl hover:scale-105 active:scale-95 transition-all cursor-pointer"
        >
          🚀 Launch AI Chatbot & 3D CAD Studio Now
        </button>
      </section>
    </div>
  );
};

export default ProductGuide;
